# Generated by Django 4.2.3 on 2025-03-16 05:12

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=database.models.upload_to),
        ),
    ]
