# Generated by Django 5.2.1 on 2025-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
