# Generated by Django 5.2.1 on 2025-07-23 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_game_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
