# Generated by Django 5.2.4 on 2025-07-23 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre_old',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
