# Generated by Django 5.2.4 on 2025-07-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_game_genre_old_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre_old',
            field=models.CharField(blank=True, default=list, max_length=50, null=True),
        ),
    ]
