# Generated by Django 5.2.4 on 2025-07-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_game_genre_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre_old',
        ),
    ]
