# Generated by Django 5.2.9 on 2025-12-11 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_game_genre_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
    ]
